### ISSUE TITLE
Load a local file

### ISSUE THREAD

**Issue by MaskyS** [dart-flitter/flutter_webview_plugin#60] opened 2018-04-09 13:14 UTC
Hi, how can I open a file that is locally stored on the device? For example, if the file index.html is located inside my project's assets folder?

**Comment by gedw99** [comment] 2018-04-09 21:18
I have exactly the same requirement.

i need to load a react app that is stored locally.  Its actually some very complex JS that i cant rewrite in Dart. It does CRDT stuff.

Once loaded i need to call certain public exported JavaScript functions. Wondering if i can use EvalJavascript Dart call. 
I also need to receive calls from inside the Webview to Dart - not sure how to do that, other than polling which is pretty bad and will kill battery.

**Comment by eugenio-tesio** [comment] 2018-04-09 22:26
I need to open a PDF file. I was thinking of doing it with a WebView. Would this be possible?

**Comment by MaskyS** [comment] 2018-04-10 06:52
I found this today, we may be able to do this, but will require changes to the plugin. See https://flutter.io/assets-and-images/#sharing-assets-with-the-underlying-platform. Another way that can work is to pass a url like "file:///data/data/com.provider.package/file_name.html" but you will need the exact file path of the HTML. I didn't manage to do this though because my assets are inside the assets folder of my project, and those are not placed in any kind of permanent directory.

**Comment by lejard-h** [comment] 2018-04-10 08:26
duplicate of https://github.com/dart-flitter/flutter_webview_plugin/issues/23

I am closing this one since we already discussed about solution in the previous one

**Closed by lejard-h** 2018-04-10 08:26 UTC

**Comment by MaskyS** [comment] 2018-04-10 08:50
@lejard-h  that solution isn't working well for me it seems. I'm getting this:  (17795): Unrecognized GLES max version string in extensions:
E/flutter (17795): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (17795): Invalid argument(s): String contains invalid characters.
E/flutter (17795): #0      _UnicodeSubsetEncoder.convert (dart:convert/ascii.dart:97:9)
E/flutter (17795): #1      AsciiCodec.encode (dart:convert/ascii.dart:47:46)
E/flutter (17795): #2      new UriData.fromString (dart:core/uri.dart:3197:44)
E/flutter (17795): #3      new Uri.dataFromString (dart:core/uri.dart:304:24)
E/flutter (17795): #4      _MyHomePageState.getUri.<anonymous closure> (file:///home/maskys/webview_test/lib/main.dart:57:21)

the widget webview remains white

**Comment by MaskyS** [comment] 2018-04-10 08:57
I think that is triggering because my html file contains quote characters?

**Comment by MaskyS** [comment] 2018-04-10 09:11
isn't the quote characters, must be something else.. Possible all the special characters in the file or the square brackets.

**Comment by Kleak** [comment] 2018-04-10 09:34
if you launch a web server you should not have problem
here is an example https://github.com/Jaguar-dart/jaguar_flutter_asset

**Comment by lejard-h** [comment] 2018-04-10 09:39
@MaskyS 

even if the solution don't work for you, it is the same issue, please continue the conversation on the other one and try the solution of @kleak describe in the article mention in the other issue
